### ISSUE TITLE
Usage: Sequence of simple mappings with standard types is failing to parse

### ISSUE THREAD

**Issue by AvlWx2014** [sksamuel/hoplite#140]
I have a YAML configuration file made up of a sequence of simple mappings like so
```yaml
- name: ICON
  row: 0
  rowSpan: 1
  column: 0
  columnSpan: 1
- name: DESCRIPTION
  row: 0
  rowSpan: 1
  column: 1
  columnSpan: 3 
```

And a data class like this:
```kotlin
data class CellSpec @JvmOverloads constructor (
    val name: String,
    val row: Int,
    val col: Int,
    val rowSpan: Int = 1,
    val colSpan: Int = 1
)
```

I am trying to load the file following examples from the README like so:
```kotlin
val sourceFile = File("table.yaml")
val cellSpecs = ConfigLoader().loadConfigOrThrow<CellSpec>(sourceFile)
```

However, I cannot seem to shake the following error:
```
com.sksamuel.hoplite.ConfigException: Error loading config because:
    
        No decoders are registered
```

Based on the docs, I would expect that since there are no types involved more complex than a sequence, which hoplite appears to support out of the box, that things would just work.

I've tried trimming it down from a list to a single object, and tried rearranging the YAML in a couple ways as shown:
```yaml
cell:
  name: ICON
  row: 0
  column: 0
  rowSpan: 1
  columnSpan: 1
```
and this so the key names match my data class fields
```yaml
- name: ICON
  row: 0
  col: 0
  rowSpan: 1
  colSpan: 1
```

but no matter what, I get the same error.

Here are the dependencies as listed in my build.gradle
```groovy
    // hoplite
    implementation 'com.sksamuel.hoplite:hoplite-core:1.3.0'
    implementation 'com.sksamuel.hoplite:hoplite-yaml:1.3.0'
```

Any guidance would be greatly appreciated.
