### ISSUE TITLE
Overwrite an array field from the ENVIRONMENT

### ISSUE THREAD

**Issue by Lawliet-L** [sksamuel/hoplite#144]
I'm using this library to configure a service that communicates with a possibly endless list of 3rd-party services, so I have something like following in my config file (example from the README for simplicity):
```
databases:
  - host: localhost
    port: 9200
    index: foo
  - host: localhost
    port: 9300
    index: bar
  - host: localhost
    port: 5234
    schema: public
    table: faz
```
Is there any way to, let's say, either specify the whole list as an ENV variable or override a specific field for specific index? Like:
```databases = [{host: localhost, post: 9200, index: not_foo}]```
``` databases__1__port = 9301 ```

**Comment by sksamuel** [comment]
I guess we could support `databases[1]__port = 9301` ?

**Comment by Lawliet-L** [comment]
Thank you for the response!
About the proposal, on the 2nd thought it might rise an issue of "dangling" elements. For example, using the list above, we add an environment variable that fully describes missing 5th element of the list and skip 4th altogether. The expected behavior of such a case is unclear and might lead to misconfiguration.
In my case it might be much easier to back every variable from the config using EnvVar Preprocessor directly, but I will lose a way to add/remove new elements to the list, which could be solved by additional configuration file to overwrite them, what do you think? What is your preferred workaround?

**Comment by sksamuel** [comment]
You mean passing the json to an env var or something else ?

**Comment by Lawliet-L** [comment]
I mean the way to use env to override a list of objects using the current version of the library.
As I can see [EnvironmentVariablesPropertySource](https://github.com/sksamuel/hoplite/blob/v1.3.0/hoplite-core/src/main/kotlin/com/sksamuel/hoplite/PropertySource.kt#L49) will be either [string node or map node](https://github.com/sksamuel/hoplite/blob/v1.3.0/hoplite-core/src/main/kotlin/com/sksamuel/hoplite/parsers/loadProps.kt#L34) but not the [ArrayNode](https://github.com/sksamuel/hoplite/blob/v1.3.0/hoplite-core/src/main/kotlin/com/sksamuel/hoplite/nodes.kt#L83)
Can we effectively use ENV to override a list of databases, which were specified using a config file:
```
databases:
  - host: localhost
    port: 9200
    index: foo
  - host: localhost
    port: 9300
    index: bar
  - host: localhost
    port: 5234
    schema: public
    table: faz
```
I ended up having a dirty solution using [EnvVar Preprocessor](https://github.com/sksamuel/hoplite/blob/v1.3.0/hoplite-core/src/main/kotlin/com/sksamuel/hoplite/preprocessor/EnvVarPreprocessor.kt#L11) like:
```
databases:
  - host: ${databases[0]__host:-localhost}
    port: ${databases[0]__port:-9200}
    index: ${databases[0]__ index:-foo}
    enabled: ${databases[0]__ enabled:-true}
 ...etc...
```
But that means I have strict length of objects in the list, and that is a very dire limitation for me. Additionally, there's no way to remove an object from the list unless it has a field like "enabled: true" in its configuration.
Have you ever used env variables to override a list of configuration objects? And what's your preferred workaround to deal with such a task?
