### ISSUE TITLE
Support for Yaml aliases

### ISSUE THREAD

**Issue by stykalin** [sksamuel/hoplite#208]
Hi! 
I saw the issue https://github.com/sksamuel/hoplite/issues/167

And as I can see in documentation [Aliases](https://bitbucket.org/asomov/snakeyaml-engine/wiki/Documentation#markdown-header-aliases) is not the same as [Merge](https://bitbucket.org/asomov/snakeyaml-engine/wiki/Documentation#markdown-header-merge)
But, when I try to use Aliases and hoplite is falls with UnsupportedOperationException.

```
d_port: &default_port 8080

services:
  - host: a_host
    port: *default_port
  - host: b_host
    port: *default_port  
```

Is it possible to add support for Aliases in yaml?
