### ISSUE TITLE
Keys with periods are not parsed correctly

### ISSUE THREAD

**Issue by erichulburd** [sksamuel/hoplite#388]
Hello, thanks for the useful library. I believe we hit an error in toml parsing that I thought I'd let you know about. We are on version `1.4.16`. Unsure if this is an issue in the latest version.

Given the following parsing function

```kt
data class Configuration (
    val value: Int = 5,
    val values: Map<String, String> = mapOf(),
)

fun parseTopicsConfig(configFile: String): Configuration {
    val configLoader = parseConfig(configFile)
    val c: Configuration = configLoader.loadConfigOrThrow()
    if (errors.size != 0) {
        Logger.getGlobal().severe(errors.toString())
        throw Exception("configuration is invalid")
    }

    return c
}

fun parseConfig(configFile: String): ConfigLoader {
    val fileName = Paths.get(configFile).toAbsolutePath().toString()
    val contents = File(fileName).readText(Charsets.UTF_8)
    return ConfigLoader.Builder()
        .addSource(TomlPropertySource(contents))
        .addSource(
            EnvironmentVariablesPropertySource(
                useUnderscoresAsSeparator = true,
                allowUppercaseNames = true,
            )
        )
        .build()
}
```

the following will fail to parse:

```toml
value = 10
[values]
"cleanup.policy" = "compact"
"delete.retention.ms" = "604800000"
```

however the following _does_ parse as expected:

```toml
value = 10
[values]
"cleanup" = "compact"
"delete" = "604800000"
```

It seems to me that keys with periods in them cause in issue. In the first case `config.values["cleanup.policy"] == null`, whereas in the second case `config.values["cleanup"] == "compact"` as expected.
