### ISSUE TITLE
Kebab case seems to fail with more than one kebab

### ISSUE THREAD

**Issue by sksamuel** [sksamuel/hoplite#66]

**Comment by davidmoshal** [comment]
seems like it fails with even one kebab, 

ie given a yaml file:
```yml
redis:
  url: redis://localhost:6379/
  request_channel: "engine-requests"
```
you get this error:
```
        - 'redis': - Could not instantiate 'RedisConfig' because:
    
            - 'request_channel': Missing from config
```
