### ISSUE TITLE
NoSuchFieldError: Companion

### ISSUE THREAD

**Issue by davidmoshal** [sksamuel/hoplite#72]
upgrade from v1.0.8 to v1.1.2 and ran into this error:
`NoSuchFieldError: Companion`
- also cpu at 100%

downgraded back to v1.0.8 and error disappeared.

config file:
```yml
env: production

redis:
  url: "redis://localhost:6379/"
  requestChannel: "foo"
  responseChannel: "foo"

odb:
  home: "db"
  configFile: "config/production.conf"
  dbFile: "engine.db" 
  server: false
  # dbFile ='abc
```
config classes:
```kt
data class EngineConfig(
        val env: String,
        val redis: RedisConfig,
        val odb: ObjectDbConfig)

data class RedisConfig(
        val url: String,
        val requestChannel: String,
        val responseChannel: String)

data class OdbConfig(
        val home: String,
        val configFile: String,
        val dbFile: String,
        val server: Boolean)
```
